services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=quartz_user
      - POSTGRES_PASSWORD=quartz_password
      - POSTGRES_DB=quartz_test
